/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  aux_sym_ident_token1 = 6,
  aux_sym_ident_token2 = 7,
  aux_sym_ident_token3 = 8,
  anon_sym_COLON = 9,
  sym_number = 10,
  anon_sym_DQUOTE = 11,
  anon_sym_LBRACE_AT = 12,
  aux_sym_string_token1 = 13,
  anon_sym_RBRACE = 14,
  sym__string_fragment = 15,
  anon_sym_LT = 16,
  anon_sym_GT = 17,
  sym__string_plain_fragment = 18,
  sym_string_escape = 19,
  anon_sym_LBRACE = 20,
  aux_sym__cpp_brace_token1 = 21,
  sym_source_file = 22,
  sym_expression = 23,
  sym_list = 24,
  sym__list_other_item = 25,
  sym__items_expect_template = 26,
  sym__items_expect_condition = 27,
  sym_vector = 28,
  sym_ident = 29,
  sym_ident_with_mode = 30,
  sym_string = 31,
  sym_string_template = 32,
  sym_string_plain = 33,
  sym_cpp = 34,
  sym__cpp_brace = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_vector_repeat1 = 37,
  aux_sym_string_repeat1 = 38,
  aux_sym_string_repeat2 = 39,
  aux_sym_string_plain_repeat1 = 40,
  aux_sym__cpp_brace_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_ident_token1] = "ident_token1",
  [aux_sym_ident_token2] = "ident_token2",
  [aux_sym_ident_token3] = "ident_token3",
  [anon_sym_COLON] = ":",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LBRACE_AT] = "{@",
  [aux_sym_string_token1] = "string_content",
  [anon_sym_RBRACE] = "}",
  [sym__string_fragment] = "_string_fragment",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym__string_plain_fragment] = "string_content",
  [sym_string_escape] = "string_escape",
  [anon_sym_LBRACE] = "{",
  [aux_sym__cpp_brace_token1] = "_cpp_brace_token1",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_list] = "list",
  [sym__list_other_item] = "_list_other_item",
  [sym__items_expect_template] = "_items_expect_template",
  [sym__items_expect_condition] = "_items_expect_condition",
  [sym_vector] = "vector",
  [sym_ident] = "ident",
  [sym_ident_with_mode] = "ident_with_mode",
  [sym_string] = "string",
  [sym_string_template] = "string_template",
  [sym_string_plain] = "string_plain",
  [sym_cpp] = "cpp",
  [sym__cpp_brace] = "_cpp_brace",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_vector_repeat1] = "vector_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym_string_plain_repeat1] = "string_plain_repeat1",
  [aux_sym__cpp_brace_repeat1] = "_cpp_brace_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_ident_token1] = aux_sym_ident_token1,
  [aux_sym_ident_token2] = aux_sym_ident_token2,
  [aux_sym_ident_token3] = aux_sym_ident_token3,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LBRACE_AT] = anon_sym_LBRACE_AT,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__string_fragment] = sym__string_fragment,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym__string_plain_fragment] = aux_sym_string_token1,
  [sym_string_escape] = sym_string_escape,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym__cpp_brace_token1] = aux_sym__cpp_brace_token1,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_list] = sym_list,
  [sym__list_other_item] = sym__list_other_item,
  [sym__items_expect_template] = sym__items_expect_template,
  [sym__items_expect_condition] = sym__items_expect_condition,
  [sym_vector] = sym_vector,
  [sym_ident] = sym_ident,
  [sym_ident_with_mode] = sym_ident_with_mode,
  [sym_string] = sym_string,
  [sym_string_template] = sym_string_template,
  [sym_string_plain] = sym_string_plain,
  [sym_cpp] = sym_cpp,
  [sym__cpp_brace] = sym__cpp_brace,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_vector_repeat1] = aux_sym_vector_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym_string_plain_repeat1] = aux_sym_string_plain_repeat1,
  [aux_sym__cpp_brace_repeat1] = aux_sym__cpp_brace_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_ident_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ident_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ident_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_fragment] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__string_plain_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__cpp_brace_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__list_other_item] = {
    .visible = false,
    .named = true,
  },
  [sym__items_expect_template] = {
    .visible = false,
    .named = true,
  },
  [sym__items_expect_condition] = {
    .visible = false,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_ident_with_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_template] = {
    .visible = true,
    .named = true,
  },
  [sym_string_plain] = {
    .visible = true,
    .named = true,
  },
  [sym_cpp] = {
    .visible = true,
    .named = true,
  },
  [sym__cpp_brace] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_plain_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__cpp_brace_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_ident = 1,
  field_mode = 2,
  field_ubexpr = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_ident] = "ident",
  [field_mode] = "mode",
  [field_ubexpr] = "ubexpr",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_ubexpr, 0},
  [1] =
    {field_ubexpr, 0},
    {field_ubexpr, 1, .inherited = true},
  [3] =
    {field_ubexpr, 1, .inherited = true},
  [4] =
    {field_ubexpr, 0, .inherited = true},
    {field_ubexpr, 1, .inherited = true},
  [6] =
    {field_ident, 0},
    {field_mode, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [0] = aux_sym_string_token1,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 29,
  [33] = 23,
  [34] = 26,
  [35] = 27,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 37,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 41,
  [45] = 42,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 22,
  [57] = 15,
  [58] = 53,
  [59] = 55,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_expression,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_expression] = {.index = 0, .length = 8},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_cpp,
    sym_ident,
    sym_ident_with_mode,
    sym_list,
    sym_number,
    sym_string,
    sym_string_plain,
    sym_vector,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 33,
        '(', 22,
        ')', 23,
        '/', 5,
        ':', 31,
        ';', 21,
        '<', 53,
        '>', 54,
        '[', 24,
        '\\', 62,
        ']', 25,
        '{', 64,
        '}', 40,
        '+', 11,
        '-', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead == '?' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(29);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 33,
        '(', 22,
        ')', 23,
        '/', 5,
        ';', 21,
        '<', 12,
        '[', 24,
        '{', 63,
        '+', 11,
        '-', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead == '?' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == ';') ADVANCE(41);
      if (lookahead == '<') ADVANCE(60);
      if (lookahead == '>') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == ';') ADVANCE(42);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == ';') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(65);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '{') ADVANCE(63);
      if (lookahead == '}') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == '}') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(39);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 33,
        '(', 22,
        ')', 23,
        '/', 5,
        ':', 31,
        ';', 21,
        '<', 53,
        '>', 54,
        '[', 24,
        ']', 25,
        '{', 64,
        '}', 40,
        '+', 11,
        '-', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead == '?' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(29);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 33,
        '(', 22,
        ')', 23,
        '/', 5,
        ':', 31,
        ';', 21,
        '<', 12,
        '[', 24,
        ']', 25,
        '{', 64,
        '+', 11,
        '-', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead == '?' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(29);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(21);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(21);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(69);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == '*' ||
          lookahead == '-') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_ident_token1);
      if (lookahead == '*' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_ident_token2);
      if (lookahead == '*' ||
          lookahead == '-') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_ident_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_ident_token3);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE_AT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(7);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(7);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == ';') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '<' ||
          lookahead == '>') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '<' ||
          lookahead == '>') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(51);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '\\') ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == '<' ||
          lookahead == '>') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '<' ||
          lookahead == '>') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '\\') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '\\') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == ';') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ';' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '\\') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == ';') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ';' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '\\') ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead == '<' ||
          lookahead == '>') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__string_fragment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '\\') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__string_plain_fragment);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__string_plain_fragment);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__string_plain_fragment);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__string_plain_fragment);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__string_plain_fragment);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == ';') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__string_plain_fragment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_string_escape);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string_escape);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '@') ADVANCE(34);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym__cpp_brace_token1);
      if (lookahead == '*') ADVANCE(67);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym__cpp_brace_token1);
      if (lookahead == '*') ADVANCE(66);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(7);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__cpp_brace_token1);
      if (lookahead == '*') ADVANCE(66);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(7);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__cpp_brace_token1);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead == ';') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__cpp_brace_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(69);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 14},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 14},
  [30] = {.lex_state = 14},
  [31] = {.lex_state = 14},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 14},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_ident_token1] = ACTIONS(1),
    [aux_sym_ident_token2] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE_AT] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_string_escape] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym_expression] = STATE(5),
    [sym_list] = STATE(25),
    [sym_vector] = STATE(25),
    [sym_ident] = STATE(19),
    [sym_ident_with_mode] = STATE(25),
    [sym_string] = STATE(25),
    [sym_string_plain] = STATE(25),
    [sym_cpp] = STATE(25),
    [sym__cpp_brace] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [aux_sym_ident_token1] = ACTIONS(11),
    [aux_sym_ident_token2] = ACTIONS(11),
    [aux_sym_ident_token3] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACE_AT] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      aux_sym_vector_repeat1,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(19), 1,
      sym_ident,
    STATE(31), 1,
      sym_expression,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(25), 6,
      sym_list,
      sym_vector,
      sym_ident_with_mode,
      sym_string,
      sym_string_plain,
      sym_cpp,
  [52] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    STATE(4), 1,
      aux_sym_vector_repeat1,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(19), 1,
      sym_ident,
    STATE(31), 1,
      sym_expression,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(25), 6,
      sym_list,
      sym_vector,
      sym_ident_with_mode,
      sym_string,
      sym_string_plain,
      sym_cpp,
  [104] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    STATE(6), 1,
      aux_sym_vector_repeat1,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(19), 1,
      sym_ident,
    STATE(31), 1,
      sym_expression,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(25), 6,
      sym_list,
      sym_vector,
      sym_ident_with_mode,
      sym_string,
      sym_string_plain,
      sym_cpp,
  [156] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(19), 1,
      sym_ident,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(7), 2,
      sym_expression,
      aux_sym_source_file_repeat1,
    STATE(25), 6,
      sym_list,
      sym_vector,
      sym_ident_with_mode,
      sym_string,
      sym_string_plain,
      sym_cpp,
  [206] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACK,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    ACTIONS(42), 1,
      aux_sym_ident_token3,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      aux_sym_vector_repeat1,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(19), 1,
      sym_ident,
    STATE(31), 1,
      sym_expression,
    ACTIONS(39), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(25), 6,
      sym_list,
      sym_vector,
      sym_ident_with_mode,
      sym_string,
      sym_string_plain,
      sym_cpp,
  [258] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      aux_sym_ident_token3,
    ACTIONS(71), 1,
      sym_number,
    ACTIONS(74), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(80), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(19), 1,
      sym_ident,
    ACTIONS(65), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(7), 2,
      sym_expression,
      aux_sym_source_file_repeat1,
    STATE(25), 6,
      sym_list,
      sym_vector,
      sym_ident_with_mode,
      sym_string,
      sym_string_plain,
      sym_cpp,
  [308] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    STATE(6), 1,
      aux_sym_vector_repeat1,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(19), 1,
      sym_ident,
    STATE(31), 1,
      sym_expression,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(25), 6,
      sym_list,
      sym_vector,
      sym_ident_with_mode,
      sym_string,
      sym_string_plain,
      sym_cpp,
  [360] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(89), 1,
      sym_number,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    ACTIONS(93), 1,
      anon_sym_LBRACE_AT,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(28), 1,
      sym_ident,
    STATE(61), 1,
      sym__items_expect_template,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(13), 2,
      sym_vector,
      sym_string,
    STATE(10), 4,
      sym_list,
      sym__list_other_item,
      sym_ident_with_mode,
      sym_cpp,
  [411] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(89), 1,
      sym_number,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    ACTIONS(93), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(28), 1,
      sym_ident,
    STATE(67), 1,
      sym__items_expect_template,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(13), 2,
      sym_vector,
      sym_string,
    STATE(10), 4,
      sym_list,
      sym__list_other_item,
      sym_ident_with_mode,
      sym_cpp,
  [462] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(89), 1,
      sym_number,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    ACTIONS(93), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(28), 1,
      sym_ident,
    STATE(60), 1,
      sym__items_expect_template,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(13), 2,
      sym_vector,
      sym_string,
    STATE(10), 4,
      sym_list,
      sym__list_other_item,
      sym_ident_with_mode,
      sym_cpp,
  [513] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(99), 1,
      sym_number,
    ACTIONS(101), 1,
      anon_sym_DQUOTE,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_vector,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(28), 1,
      sym_ident,
    STATE(62), 1,
      sym__items_expect_condition,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(9), 5,
      sym_list,
      sym__list_other_item,
      sym_ident_with_mode,
      sym_string_plain,
      sym_cpp,
  [561] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 1,
      sym_number,
    ACTIONS(101), 1,
      anon_sym_DQUOTE,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_vector,
    STATE(16), 1,
      sym__cpp_brace,
    STATE(28), 1,
      sym_ident,
    STATE(65), 1,
      sym__items_expect_condition,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    STATE(9), 5,
      sym_list,
      sym__list_other_item,
      sym_ident_with_mode,
      sym_string_plain,
      sym_cpp,
  [609] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(105), 10,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      anon_sym_COLON,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [630] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(109), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [650] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(113), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [670] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(117), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [690] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(121), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [710] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_COLON,
    ACTIONS(127), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(125), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(131), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [752] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(135), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [772] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(139), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [792] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [811] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [830] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(125), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [849] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(153), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [868] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(157), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [887] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_COLON,
    ACTIONS(163), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(161), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [908] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(165), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [927] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(169), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [945] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 3,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
      anon_sym_LBRACE,
    ACTIONS(173), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_AT,
  [963] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    ACTIONS(165), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [980] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    ACTIONS(143), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    ACTIONS(153), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [1014] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
    ACTIONS(157), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      aux_sym_ident_token3,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [1031] = 8,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      sym__string_fragment,
    ACTIONS(183), 1,
      anon_sym_LT,
    ACTIONS(185), 1,
      sym__string_plain_fragment,
    ACTIONS(187), 1,
      sym_string_escape,
    STATE(52), 1,
      aux_sym_string_plain_repeat1,
    STATE(37), 2,
      sym_string_template,
      aux_sym_string_repeat1,
  [1057] = 6,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LT,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    ACTIONS(191), 1,
      sym__string_fragment,
    ACTIONS(193), 1,
      sym_string_escape,
    STATE(39), 2,
      sym_string_template,
      aux_sym_string_repeat1,
  [1077] = 6,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LT,
    ACTIONS(191), 1,
      sym__string_fragment,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
    ACTIONS(197), 1,
      sym_string_escape,
    STATE(40), 2,
      sym_string_template,
      aux_sym_string_repeat1,
  [1097] = 6,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    ACTIONS(201), 1,
      sym__string_fragment,
    ACTIONS(204), 1,
      anon_sym_LT,
    ACTIONS(207), 1,
      sym_string_escape,
    STATE(39), 2,
      sym_string_template,
      aux_sym_string_repeat1,
  [1117] = 6,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LT,
    ACTIONS(191), 1,
      sym__string_fragment,
    ACTIONS(193), 1,
      sym_string_escape,
    ACTIONS(210), 1,
      anon_sym_DQUOTE,
    STATE(39), 2,
      sym_string_template,
      aux_sym_string_repeat1,
  [1137] = 5,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      aux_sym__cpp_brace_token1,
    STATE(45), 2,
      sym__cpp_brace,
      aux_sym__cpp_brace_repeat1,
  [1154] = 5,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    ACTIONS(220), 1,
      aux_sym__cpp_brace_token1,
    STATE(43), 2,
      sym__cpp_brace,
      aux_sym__cpp_brace_repeat1,
  [1171] = 5,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      aux_sym__cpp_brace_token1,
    STATE(43), 2,
      sym__cpp_brace,
      aux_sym__cpp_brace_repeat1,
  [1188] = 5,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    ACTIONS(232), 1,
      aux_sym__cpp_brace_token1,
    STATE(42), 2,
      sym__cpp_brace,
      aux_sym__cpp_brace_repeat1,
  [1205] = 5,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 1,
      aux_sym__cpp_brace_token1,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(43), 2,
      sym__cpp_brace,
      aux_sym__cpp_brace_repeat1,
  [1222] = 5,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    ACTIONS(241), 1,
      sym__string_plain_fragment,
    ACTIONS(243), 1,
      sym_string_escape,
    ACTIONS(239), 2,
      sym__string_fragment,
      anon_sym_LT,
  [1239] = 3,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(246), 2,
      anon_sym_DQUOTE,
      anon_sym_LT,
    ACTIONS(248), 2,
      sym__string_fragment,
      sym_string_escape,
  [1251] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      aux_sym_string_plain_repeat1,
    ACTIONS(252), 2,
      sym__string_plain_fragment,
      sym_string_escape,
  [1265] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      aux_sym_ident_token3,
    STATE(21), 1,
      sym_ident,
    ACTIONS(11), 2,
      aux_sym_ident_token1,
      aux_sym_ident_token2,
  [1279] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      aux_sym_string_plain_repeat1,
    ACTIONS(257), 2,
      sym__string_plain_fragment,
      sym_string_escape,
  [1293] = 3,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(259), 2,
      anon_sym_DQUOTE,
      anon_sym_LT,
    ACTIONS(261), 2,
      sym__string_fragment,
      sym_string_escape,
  [1305] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      aux_sym_string_plain_repeat1,
    ACTIONS(265), 2,
      sym__string_plain_fragment,
      sym_string_escape,
  [1319] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    ACTIONS(267), 1,
      aux_sym_string_token1,
    STATE(54), 1,
      aux_sym_string_repeat2,
  [1332] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(269), 1,
      aux_sym_string_token1,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_string_repeat2,
  [1345] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(274), 1,
      aux_sym_string_token1,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      aux_sym_string_repeat2,
  [1358] = 2,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      aux_sym__cpp_brace_token1,
  [1367] = 2,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(111), 3,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      aux_sym__cpp_brace_token1,
  [1376] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    ACTIONS(267), 1,
      aux_sym_string_token1,
    STATE(54), 1,
      aux_sym_string_repeat2,
  [1389] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    ACTIONS(278), 1,
      aux_sym_string_token1,
    STATE(58), 1,
      aux_sym_string_repeat2,
  [1402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
  [1409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
  [1416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
  [1423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_GT,
  [1430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      ts_builtin_sym_end,
  [1437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
  [1444] = 2,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(290), 1,
      sym__string_fragment,
  [1451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 104,
  [SMALL_STATE(5)] = 156,
  [SMALL_STATE(6)] = 206,
  [SMALL_STATE(7)] = 258,
  [SMALL_STATE(8)] = 308,
  [SMALL_STATE(9)] = 360,
  [SMALL_STATE(10)] = 411,
  [SMALL_STATE(11)] = 462,
  [SMALL_STATE(12)] = 513,
  [SMALL_STATE(13)] = 561,
  [SMALL_STATE(14)] = 609,
  [SMALL_STATE(15)] = 630,
  [SMALL_STATE(16)] = 650,
  [SMALL_STATE(17)] = 670,
  [SMALL_STATE(18)] = 690,
  [SMALL_STATE(19)] = 710,
  [SMALL_STATE(20)] = 732,
  [SMALL_STATE(21)] = 752,
  [SMALL_STATE(22)] = 772,
  [SMALL_STATE(23)] = 792,
  [SMALL_STATE(24)] = 811,
  [SMALL_STATE(25)] = 830,
  [SMALL_STATE(26)] = 849,
  [SMALL_STATE(27)] = 868,
  [SMALL_STATE(28)] = 887,
  [SMALL_STATE(29)] = 908,
  [SMALL_STATE(30)] = 927,
  [SMALL_STATE(31)] = 945,
  [SMALL_STATE(32)] = 963,
  [SMALL_STATE(33)] = 980,
  [SMALL_STATE(34)] = 997,
  [SMALL_STATE(35)] = 1014,
  [SMALL_STATE(36)] = 1031,
  [SMALL_STATE(37)] = 1057,
  [SMALL_STATE(38)] = 1077,
  [SMALL_STATE(39)] = 1097,
  [SMALL_STATE(40)] = 1117,
  [SMALL_STATE(41)] = 1137,
  [SMALL_STATE(42)] = 1154,
  [SMALL_STATE(43)] = 1171,
  [SMALL_STATE(44)] = 1188,
  [SMALL_STATE(45)] = 1205,
  [SMALL_STATE(46)] = 1222,
  [SMALL_STATE(47)] = 1239,
  [SMALL_STATE(48)] = 1251,
  [SMALL_STATE(49)] = 1265,
  [SMALL_STATE(50)] = 1279,
  [SMALL_STATE(51)] = 1293,
  [SMALL_STATE(52)] = 1305,
  [SMALL_STATE(53)] = 1319,
  [SMALL_STATE(54)] = 1332,
  [SMALL_STATE(55)] = 1345,
  [SMALL_STATE(56)] = 1358,
  [SMALL_STATE(57)] = 1367,
  [SMALL_STATE(58)] = 1376,
  [SMALL_STATE(59)] = 1389,
  [SMALL_STATE(60)] = 1402,
  [SMALL_STATE(61)] = 1409,
  [SMALL_STATE(62)] = 1416,
  [SMALL_STATE(63)] = 1423,
  [SMALL_STATE(64)] = 1430,
  [SMALL_STATE(65)] = 1437,
  [SMALL_STATE(66)] = 1444,
  [SMALL_STATE(67)] = 1451,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5), SHIFT_REPEAT(11),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5), SHIFT_REPEAT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5), SHIFT_REPEAT(14),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5), SHIFT_REPEAT(14),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5), SHIFT_REPEAT(25),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5), SHIFT_REPEAT(36),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5), SHIFT_REPEAT(55),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 5), SHIFT_REPEAT(44),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items_expect_condition, 1, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items_expect_template, 1, 0, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ident, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ident, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cpp_brace, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cpp_brace, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cpp, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cpp, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 4),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_plain, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_plain, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ident_with_mode, 3, 0, 6),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ident_with_mode, 3, 0, 6),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cpp_brace, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cpp_brace, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_string, 2, 0, 0), REDUCE(sym_string_plain, 2, 0, 0),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_string, 2, 0, 0), REDUCE(sym_string_plain, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 3, 0, 4),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 3, 0, 4),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_other_item, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__list_other_item, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_plain, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_plain, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 1, 0, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_vector_repeat1, 1, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__cpp_brace_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__cpp_brace_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__cpp_brace_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [236] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0), REDUCE(aux_sym_string_plain_repeat1, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_plain_repeat1, 1, 0, 0),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0), REDUCE(aux_sym_string_plain_repeat1, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_template, 3, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_template, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_plain_repeat1, 2, 0, 0),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_plain_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 2),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 2),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(54),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [278] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items_expect_condition, 2, 0, 3),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [286] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items_expect_template, 2, 0, 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gcc_md(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gcc_md",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
